version: "3.8"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=articlesDB
      - POSTGRES_USER=janire
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8088:8080"

  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://janire:password@database:5432/articlesDB
    restart: always

  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8005:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apk:/usr/share/nginx/html/apk
    depends_on:
      - backend
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped

volumes:
  portainer_data:
